import { useEffect,useMemo,useRef,useState } from "react"; import { ImageUp,Pencil,Plus,Power,Trash2,X } from "lucide-react"; import { toast } from "sonner"; import { supabase } from "@/lib/supabase"; import { uploadSiteImage } from "@/lib/siteDrive";
type P={id:string;title:string;eyebrow:string|null;description:string|null;image_url:string|null;youtube_url:string|null;cta_label:string;cta_url:string|null;active:boolean};
type M={id:string;slug:string;titulo:string;resumo:string|null;capa_url:string|null;capa_thumb_url:string|null;published_at:string|null};
const blank={title:"",eyebrow:"Novidade",description:"",image_url:"",youtube_url:"",cta_label:"Assistir agora",cta_url:"",active:false};
export function AdminPopups(){const [items,setItems]=useState<P[]>([]),[materias,setMaterias]=useState<M[]>([]),[form,setForm]=useState(blank),[edit,setEdit]=useState<string|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[source,setSource]=useState<"custom"|"materia">("custom"),[materiaId,setMateriaId]=useState(""),[uploading,setUploading]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
async function load(){const [{data,error},{data:ms,error:me}]=await Promise.all([supabase.from("site_popups").select("*").order("created_at",{ascending:false}),supabase.from("materias").select("id,slug,titulo,resumo,capa_url,capa_thumb_url,published_at").eq("status","published").order("published_at",{ascending:false})]);error?toast.error(error.message):setItems((data||[]) as P[]);if(me)toast.error("Não foi possível carregar as matérias.");else setMaterias((ms||[]) as M[])} useEffect(()=>{void load()},[]);
function start(p?:P){setSource("custom");setMateriaId("");if(p){setEdit(p.id);setForm({title:p.title,eyebrow:p.eyebrow||"",description:p.description||"",image_url:p.image_url||"",youtube_url:p.youtube_url||"",cta_label:p.cta_label,cta_url:p.cta_url||"",active:p.active})}else{setEdit(null);setForm(blank)}setOpen(true)}
function chooseMateria(id:string){setMateriaId(id);const m=materias.find(x=>x.id===id);if(!m)return;setForm(v=>({...v,eyebrow:"Matéria em destaque",title:m.titulo,description:m.resumo||"",image_url:m.capa_thumb_url||m.capa_url||"",youtube_url:"",cta_label:"Ler matéria",cta_url:`${window.location.origin}/materias/${m.slug}`}))}
async function uploadThumb(file?:File){if(!file)return;setUploading(true);try{const url=await uploadSiteImage(file,"popup");setForm(v=>({...v,image_url:url}));toast.success("Thumbnail enviada ao Drive RKC.");}catch(e){toast.error(e instanceof Error?e.message:"Falha no upload da thumbnail.");}finally{setUploading(false)}}
async function save(){if(!form.title.trim())return toast.error("Informe o título.");setBusy(true);const payload={...form,title:form.title.trim(),eyebrow:form.eyebrow||null,description:form.description||null,image_url:form.image_url||null,youtube_url:form.youtube_url||null,cta_url:form.cta_url||form.youtube_url||null};const {error}=edit?await supabase.from("site_popups").update(payload).eq("id",edit):await supabase.from("site_popups").insert(payload);setBusy(false);if(error)return toast.error(error.message);toast.success("Pop-up salvo.");setOpen(false);await load()}
async function toggle(p:P){const {error}=await supabase.from("site_popups").update({active:!p.active}).eq("id",p.id);if(error)toast.error(error.message);else{toast.success(!p.active?"Ativado; o anterior foi desativado.":"Desativado.");await load()}}
async function del(p:P){if(!confirm(`Excluir “${p.title}”?`))return;const {error}=await supabase.from("site_popups").delete().eq("id",p.id);if(error)toast.error(error.message);else await load()}
const preview=useMemo(()=>form,[form]);
return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold">Pop-ups</h1><p className="mt-1 text-muted-foreground">Destaques da página inicial. Apenas um fica ativo por vez.</p></div><button onClick={()=>start()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 font-semibold text-primary-foreground"><Plus className="h-4 w-4"/>Novo pop-up</button></div>
<div className="grid gap-4">{items.map(p=><div key={p.id} className="flex flex-col gap-4 rounded-xl border bg-card p-4 sm:flex-row sm:items-center"><div className="h-24 w-full overflow-hidden rounded-lg bg-muted sm:w-40">{p.image_url?<img src={p.image_url} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-xs text-muted-foreground">Sem imagem</div>}</div><div className="min-w-0 flex-1"><div className="flex gap-2"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${p.active?"bg-green-100 text-green-700":"bg-muted text-muted-foreground"}`}>{p.active?"ATIVO":"INATIVO"}</span><span className="text-xs text-muted-foreground">{p.eyebrow}</span></div><h2 className="mt-2 text-lg font-bold">{p.title}</h2><p className="line-clamp-2 text-sm text-muted-foreground">{p.description}</p></div><div className="flex gap-2"><button onClick={()=>toggle(p)} className={`rounded-md border p-2 transition-colors ${p.active?"border-green-600 bg-green-600 text-white hover:bg-green-700":"text-muted-foreground hover:border-green-500 hover:text-green-700"}`} title={p.active?"Ligado — clique para desativar":"Desligado — clique para ativar"} aria-pressed={p.active}><Power className="h-4 w-4"/></button><button onClick={()=>start(p)} className="rounded-md border p-2"><Pencil className="h-4 w-4"/></button><button onClick={()=>del(p)} className="rounded-md border p-2 text-destructive"><Trash2 className="h-4 w-4"/></button></div></div>)}{!items.length&&<div className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">Nenhum pop-up criado.</div>}</div>
{open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4"><div className="max-h-[94vh] w-full max-w-5xl overflow-y-auto rounded-2xl bg-background p-6 shadow-2xl"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-bold">{edit?"Editar":"Novo"} pop-up</h2><p className="text-sm text-muted-foreground">Crie manualmente ou reaproveite uma matéria publicada.</p></div><button onClick={()=>setOpen(false)}><X/></button></div>
<div className="grid gap-6 lg:grid-cols-[1fr_0.9fr]"><div className="space-y-4"><div><span className="mb-2 block text-sm font-semibold">Origem do conteúdo</span><div className="grid grid-cols-2 gap-2"><button onClick={()=>{setSource("custom");setMateriaId("")}} className={`rounded-lg border p-3 text-sm font-semibold ${source==="custom"?"border-primary bg-primary/10 text-primary":""}`}>Personalizado</button><button onClick={()=>setSource("materia")} className={`rounded-lg border p-3 text-sm font-semibold ${source==="materia"?"border-primary bg-primary/10 text-primary":""}`}>Matéria publicada</button></div></div>
{source==="materia"&&<label><span className="mb-1 block text-sm font-medium">Escolha uma matéria</span><select value={materiaId} onChange={e=>chooseMateria(e.target.value)} className="h-11 w-full rounded-md border bg-background px-3"><option value="">Selecione...</option>{materias.map(m=><option key={m.id} value={m.id}>{m.titulo}</option>)}</select><span className="mt-1 block text-xs text-muted-foreground">Título, resumo, capa e link são preenchidos automaticamente e continuam editáveis.</span></label>}
<div className="grid gap-4 sm:grid-cols-2">{([["eyebrow","Etiqueta"],["title","Título"],["youtube_url","Link do YouTube"],["cta_label","Texto do botão"],["cta_url","Link do botão"]] as const).map(([k,l])=><label key={k} className={k==="title"?"sm:col-span-2":""}><span className="mb-1 block text-sm font-medium">{l}</span><input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="h-10 w-full rounded-md border bg-background px-3"/></label>)}<div className="sm:col-span-2"><span className="mb-1 block text-sm font-medium">Thumbnail / imagem</span><div className="flex flex-col gap-2 sm:flex-row"><input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="URL da imagem ou faça upload" className="h-10 min-w-0 flex-1 rounded-md border bg-background px-3"/><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="hidden" onChange={e=>{void uploadThumb(e.target.files?.[0]);e.currentTarget.value=""}}/><button type="button" disabled={uploading} onClick={()=>fileRef.current?.click()} className="inline-flex h-10 items-center justify-center gap-2 rounded-md border px-4 font-semibold hover:bg-muted disabled:opacity-60"><ImageUp className="h-4 w-4"/>{uploading?"Enviando...":form.image_url?"Trocar thumbnail":"Enviar thumbnail"}</button></div><span className="mt-1 block text-xs text-muted-foreground">JPEG, PNG, WebP ou GIF, até 25 MB. O arquivo vai para o Drive institucional da RKC.</span></div><label className="sm:col-span-2"><span className="mb-1 block text-sm font-medium">Descrição</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="min-h-24 w-full rounded-md border bg-background p-3"/></label><label className="flex items-center gap-2 sm:col-span-2"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Ativar ao salvar (desativa automaticamente o anterior)</label></div></div>
<div><p className="mb-2 text-sm font-semibold">Pré-visualização</p><div className="overflow-hidden rounded-2xl border bg-white shadow-lg">{preview.image_url?<img src={preview.image_url} alt="" className="aspect-video w-full object-cover"/>:<div className="flex aspect-video items-center justify-center bg-muted text-sm text-muted-foreground">Imagem/thumbnail</div>}<div className="p-5">{preview.eyebrow&&<span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold uppercase text-green-800">{preview.eyebrow}</span>}<h3 className="mt-3 text-2xl font-bold text-slate-900">{preview.title||"Título do destaque"}</h3><p className="mt-2 text-sm text-slate-600">{preview.description||"A descrição aparecerá aqui."}</p><span className="mt-4 inline-block rounded-lg bg-[#0F7A3E] px-4 py-2 text-sm font-semibold text-white">{preview.cta_label||"Saiba mais"}</span></div></div></div></div>
<div className="mt-6 flex justify-end gap-2"><button onClick={()=>setOpen(false)} className="rounded-md border px-4 py-2">Cancelar</button><button disabled={busy} onClick={save} className="rounded-md bg-primary px-4 py-2 font-semibold text-primary-foreground">{busy?"Salvando...":"Salvar pop-up"}</button></div></div></div>}</div>
}