import { Paperclip, Pencil, Trash2, X } from "lucide-react";
import type { FormEvent } from "react";
import { useState } from "react";
import { cn } from "@/app/components/ui/utils";
import { priorityBadgeClass, statusBadgeClass, taskBrandTheme } from "./tasksTheme";
import type { Task, TaskFormValues, TeamProfile } from "./tasksTypes";

export const PriorityBadge = ({ prioridade }: { prioridade: Task["prioridade"] }) => <span className={cn("rounded-full border px-2 py-0.5 text-xs font-medium", priorityBadgeClass[prioridade])}>{prioridade}</span>;
export function UserMultiSelect({ users, value, onChange }: { users: TeamProfile[]; value: string[]; onChange: (ids: string[]) => void }) { return <div className="space-y-1">{users.map((u)=><label key={u.id} className="flex gap-2"><input type="checkbox" checked={value.includes(u.id)} onChange={(e)=>onChange(e.target.checked?[...new Set([...value,u.id])]:value.filter((id)=>id!==u.id))}/>{u.nome||u.email||"Usuário"}</label>)}</div>; }
export function TaskTabs({tab,onChange}:{tab:"detalhes"|"arquivos"|"direcionamento";onChange:(tab:"detalhes"|"arquivos"|"direcionamento")=>void}){return <div className="grid grid-cols-3 gap-2">{(["detalhes","arquivos","direcionamento"] as const).map((t)=><button key={t} type="button" onClick={()=>onChange(t)} className={cn("rounded border p-1",tab===t&&"bg-emerald-50 border-emerald-500")}>{t}</button>)}</div>;}

export function TasksCalendarGrid({calendarDays,monthStartOffset,month,selectedDateKey,taskCountByDate,onSelectDate,onPrevMonth,onNextMonth,isLoading}:{calendarDays:Date[];monthStartOffset:number;month:Date;selectedDateKey:string;taskCountByDate:Map<string,number>;onSelectDate:(d:Date)=>void;onPrevMonth:()=>void;onNextMonth:()=>void;isLoading:boolean;}){return <section className="rounded-2xl border p-4" style={{["--brand-primary" as string]:taskBrandTheme.brandPrimary}}><div className="flex justify-between"><button onClick={onPrevMonth}>◀</button><p>{month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</p><button onClick={onNextMonth}>▶</button></div><div className="mt-2 grid grid-cols-7 gap-2">{Array.from({length:monthStartOffset}).map((_,i)=><div key={i}/>) }{calendarDays.map((day)=>{const key=`${day.getFullYear()}-${`${day.getMonth()+1}`.padStart(2,"0")}-${`${day.getDate()}`.padStart(2,"0")}`;const count=taskCountByDate.get(key)??0;return <button key={key} onClick={()=>onSelectDate(day)} className={cn("rounded border p-2 text-left",key===selectedDateKey&&"border-emerald-500")}><div>{day.getDate()}</div><div>{count} tarefas</div></button>;})}</div>{isLoading&&<p>Carregando...</p>}</section>}

export function TasksDrawer(props:{isOpen:boolean;selectedDate:Date;tasksOfDay:Task[];canManage:boolean;teamLoading:boolean;teamError:string|null;isSaving:boolean;saveSuccess:string|null;form:TaskFormValues;users:TeamProfile[];userNameById:Map<string,string>;files:File[];saveError:string|null;tasksDayLoading:boolean;onClose:()=>void;onSubmit:(e:FormEvent)=>void;onFormChange:(v:Partial<TaskFormValues>)=>void;onFilesChange:(f:File[])=>void;onEditTask:(t:Task)=>void;onDeleteTask:(id:string)=>void;responsibleName:string;}){
const [tab,setTab]=useState<"detalhes"|"arquivos"|"direcionamento">("detalhes");
if(!props.isOpen) return null;
return <div className="fixed inset-0 z-50 flex justify-end bg-black/45"><div className="h-full w-full max-w-2xl overflow-y-auto bg-slate-50 p-5"><button onClick={props.onClose}><X/></button>
{props.tasksOfDay.map((task)=><article key={task.id}><div className="flex gap-2"><PriorityBadge prioridade={task.prioridade}/><span className={cn("rounded-full border px-2 py-0.5 text-xs",statusBadgeClass[task.status])}>{task.status}</span><button onClick={()=>props.onEditTask(task)}><Pencil/></button><button onClick={()=>props.onDeleteTask(task.id)}><Trash2/></button></div><p>{task.titulo}</p><p>Responsável: {props.userNameById.get(task.assigned_to??"")||"-"}</p><p>Direcionamento: {(task.direcionamento||[]).map((id)=>props.userNameById.get(id)||id).join(", ")||"-"}</p>{(task.task_attachments??[]).map((a)=><p key={a.id}><Paperclip/>{a.file_name||"Anexo"}</p>)}</article>)}
<form onSubmit={props.onSubmit} className="space-y-2"><TaskTabs tab={tab} onChange={setTab}/>{tab==="detalhes"&&<><input value={props.form.titulo} onChange={(e)=>props.onFormChange({titulo:e.target.value})} placeholder="Título" required/><textarea value={props.form.descricao} onChange={(e)=>props.onFormChange({descricao:e.target.value})}/><input value={props.responsibleName} readOnly/><input type="date" value={props.form.data_inicial} onChange={(e)=>props.onFormChange({data_inicial:e.target.value})}/><input type="date" value={props.form.data_final} onChange={(e)=>props.onFormChange({data_final:e.target.value})}/><select value={props.form.prioridade} onChange={(e)=>props.onFormChange({prioridade:e.target.value as TaskFormValues['prioridade']})}><option value="urgente">Urgente</option><option value="alta">Alta</option><option value="media">Média</option><option value="baixa">Baixa</option><option value="concluida">Concluída</option></select></>}{tab==="arquivos"&&<><input type="file" multiple onChange={(e)=>props.onFilesChange(Array.from(e.target.files??[]))}/><textarea value={props.form.observacoes} onChange={(e)=>props.onFormChange({observacoes:e.target.value})}/></>}{tab==="direcionamento"&&<UserMultiSelect users={props.users} value={props.form.direcionamento} onChange={(ids)=>props.onFormChange({direcionamento:ids})}/>}<button disabled={props.isSaving}>{props.isSaving?"Salvando...":"Salvar"}</button></form></div></div>;
}
