import type { DriveFileRecord } from "@/services/driveFiles";
export type Status = "draft" | "review" | "published" | "archived";
export type Course = {
  id: string;
  title: string;
  slug: string;
  summary: string;
  description: string;
  cover_path: string | null;
  cover_drive_file_id: string | null;
  banner_drive_file_id: string | null;
  created_by: string | null;
  category_id: string | null;
  level: string;
  hours: number;
  objectives: string;
  competencies: string[];
  audience: string;
  prerequisites: string;
  status: Status;
  visibility: "internal" | "public";
  access_mode: "internal" | "free" | "paid";
  price: number;
  currency: string;
  enrollment_mode: "manual" | "self" | "automatic";
  required: boolean;
  position: number;
  available_from: string | null;
  available_until: string | null;
  published_at: string | null;
};
export type Module = {
  id: string;
  course_id: string;
  title: string;
  description: string;
  position: number;
};
export type Lesson = {
  id: string;
  course_id: string;
  module_id: string;
  title: string;
  description: string;
  content: string;
  type: string;
  media_url: string | null;
  media_path: string | null;
  media_source: "none" | "drive" | "youtube" | "vimeo";
  media_drive_file_id: string | null;
  thumbnail_drive_file_id: string | null;
  duration_minutes: number;
  position: number;
  required: boolean;
  status: string;
  context_route: string | null;
  context_feature: string | null;
};
export type Material = {
  id: string;
  course_id: string;
  lesson_id: string | null;
  title: string;
  storage_path: string | null;
  drive_file_id: string | null;
  url: string | null;
};
export type Enrollment = {
  id: string;
  course_id: string;
  user_id: string;
  status: string;
  source: string;
  required: boolean;
  enrolled_at: string;
  completed_at: string | null;
  last_lesson_id: string | null;
};
export type Progress = {
  enrollment_id: string;
  course_id: string;
  lesson_id: string;
  started_at: string;
  completed_at: string | null;
};
export type Activity = {
  id: string;
  course_id: string;
  lesson_id: string | null;
  title: string;
  instructions: string;
  kind: "activity" | "assessment";
  required: boolean;
  passing_score: number;
  max_attempts: number;
  status: string;
};
export type Question = {
  id: string;
  activity_id: string;
  prompt: string;
  type: string;
  options: string[];
  points: number;
  position: number;
  time_limit_seconds: number | null;
};
export type Attempt = {
  id: string;
  course_id: string;
  enrollment_id: string;
  activity_id: string;
  attempt_number: number;
  score: number | null;
  status: string;
  submitted_at: string;
};
export type Answer = {
  id: string;
  attempt_id: string;
  question_id: string;
  answer: string;
  points_awarded: number | null;
  correct: boolean | null;
  elapsed_seconds: number;
  feedback: string;
};
export type Contribution = {
  id: string;
  user_id: string;
  course_id: string | null;
  title: string;
  content: string;
  reference_url: string | null;
  status: string;
  review_notes: string;
  created_at: string;
  reviewed_by: string | null;
  reviewed_at: string | null;
};
export type Member = { id: string; nome: string; user_id: string | null };
export type Category = { id: string; name: string };
export type Instructor = {
  id: string;
  member_id: string | null;
  external_name: string | null;
  bio: string;
};
export type CourseInstructor = {
  course_id: string;
  instructor_id: string;
  can_edit: boolean;
};
export type Report = {
  course_title: string;
  competencies: string[];
  hours: number;
  enrollment_id: string;
  course_id: string;
  user_id: string;
  total_units: number;
  completed_units: number;
  progress: number;
  completed_at: string | null;
  last_lesson_id: string | null;
};
export type Settings = { id: boolean; title: string; welcome_text: string };
export type AcademyData = {
  driveFiles: DriveFileRecord[];
  courses: Course[];
  categories: Category[];
  modules: Module[];
  lessons: Lesson[];
  materials: Material[];
  enrollments: Enrollment[];
  progress: Progress[];
  activities: Activity[];
  questions: Question[];
  attempts: Attempt[];
  answers: Answer[];
  contributions: Contribution[];
  instructors: Instructor[];
  courseInstructors: CourseInstructor[];
  members: Member[];
  reports: Report[];
  settings: Settings[];
};
